apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ""
spec:
  selector:
    matchLabels:
      app: ""
  replicas: 1
  template:
    metadata:
      labels:
        app: ""
    spec:
      volumes:
        - name: repo-pv-storage
          hostPath:
            path: /tmp/repo-pv
            type: Directory
#      initContainers:
#        - name: git-clone
#          image: alpine/git
#          command:
#            - git
#            - clone
#            - 'https://myProjectGitRpo.git' # todo update
#            - /project
#          volumeMounts:
#            - mountPath: /project
#              name: repo-pv-storage
      containers:
        - name: ""
          image: localhost/devpod-java-test:0.0.1
          command: ["sleep", "infinity"]
          volumeMounts:
            - mountPath: /repo
              name: repo-pv-storage
          imagePullPolicy: Never
