apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ""
  namespace: cncf
spec:
  selector:
    matchLabels:
      app: ""
  replicas: 1
  template:
    metadata:
      labels:
        app: ""
    spec:
      containers:
        - name: ""
          image: java-devpod
          imagePullPolicy: Never
          command: ["sleep", "infinity"]
          volumeMounts:
            - mountPath: /root
              name: repo-pv-storage
      volumes:
        - name: repo-pv-storage
          persistentVolumeClaim:
            claimName: ""
