apiVersion: v1
kind: PersistentVolume
metadata:
  name: ""
  namespace: cncf
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 256Mi
  storageClassName: standard
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /mount/repo