apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ""
  namespace: cncf
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  volumeName: ""