apiVersion: apps/v1
kind: Deployment
metadata:
  name: devpod-operator
  namespace: cncf
  labels:
    app: devpod-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: devpod-operator
  template:
    metadata:
      labels:
        app: devpod-operator
    spec:
      serviceAccountName: devpod-operator-sa
      containers:
        - name: devpod-operator
          image: devpod-operator
          ports:
            - containerPort: 80
          imagePullPolicy: Never

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devpod-operator-sa
  namespace: cncf

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devpod-operator-cr
  namespace: cncf
rules:
  - apiGroups:
      - ""
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - "apps"
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - com.cncf
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - "*"
      - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: devpod-operator-crb
  namespace: cncf
subjects:
  - kind: ServiceAccount
    name: devpod-operator-sa
    namespace: cncf
roleRef:
  kind: ClusterRole
  name: devpod-operator-cr
  apiGroup: rbac.authorization.k8s.io

#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: repo-pv
#  namespace: cncf
#spec:
#  accessModes:
#    - ReadWriteOnce
#  capacity:
#    storage: 1Gi
#  storageClassName: standard-rwo
#  hostPath:
#    path: /tmp/repo-pv

#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: repo-pv-claim
#  namespace: cncf
#spec:
#  storageClassName: standard-rwo
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 1Gi