kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  kubeProxyMode: "ipvs"
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: KubeProxyConfiguration
        ipvs:
          strictARP: true
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: KubeProxyConfiguration
        ipvs:
          strictARP: true
    extraPortMappings:
      - containerPort: 80
        hostPort: 81
        protocol: TCP
    extraMounts:
      - hostPath: /Users/em6115358/Documents/personal/cncf/devpod-operator
        containerPath: /mount/repo

